## 실행명령목록

```{r web-interface, eval=FALSE, filename="vs code 터미널"}
uvicorn nmdose.main:app --reload --host 127.0.0.1 --port 8001
```

```{r to-orthanc, eval=FALSE, filename="PowerShell"}
python src/nmdose/run.py --loglevel debug
```

```{r to-nmdose, eval=FALSE, filename="PowerShell"}
C:\nmdose\bin\retrieving_to_nmdose.ps1
```

```{r to-dicoogle, eval=FALSE, filename="PowerShell"}
C:\nmdose\bin\retrieving_to_dicoogle.ps1
```

## 일회성코드

```{r dicom_instance, eval=FALSE, filename="pqsl"}
CREATE TABLE IF NOT EXISTS dicom_instances (
  instance_uid   TEXT        PRIMARY KEY,
  log_id         INTEGER     NOT NULL,
  file_path      TEXT        NOT NULL,
  file_size      BIGINT      NOT NULL,
  checksum       TEXT        NOT NULL,
  received_time  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  FOREIGN KEY(log_id) REFERENCES dicom_transfer_logs(id)
);
```

## powershell에서 개발을 파이썬으로 변경하였다.

## 모듈
모듈파일을 불러오기 위해서 대화형 인터프리터가 해당 폴더에서 열려야 한다.

"import 모듈_이름"으로 불러오기가 된다.
모듈안의 함수는 도트인자를 사용한다.
그런데 함수를 직접 import 하면 도트인자없이 사용할 수 있다.
from 모듈_이름 import 모듈_함수


