rpacs_admin:
  database: postgres       # 시스템 기본 DB
  user:     postgres       # 슈퍼유저 계정
  host:     127.0.0.1
  port:     5432

rpacs:
  database: rpacs
  user:     nmuser         # 일반 애플리케이션 계정
  host:     127.0.0.1
  port:     5432
