clinicalPACS:
  aet: NMPACS
  ip: 172.17.111.214
  port: 104

simulationPACS:
  aet: NMFULLDATA
  ip: 127.0.0.1
  port: 5680

researchPACS:
  aet: ORTHANC
  ip: 127.0.0.1
  port: 4242

dosePACS:
  aet: NMDOSE
  ip: 127.0.0.1
  port: 5678