tables:
  dose_statistics:
    comment: "SR 시리즈에서 추출한 방사선 선량 정보 저장 테이블"
    columns:
      - name: study_instance_uid
        type: text
        primary_key: true
        comment: "DICOM StudyInstanceUID (고유 식별자)"

      - name: series_instance_uid
        type: text
        comment: "SR 시리즈의 SeriesInstanceUID"

      - name: sop_instance_uid
        type: text
        comment: "SR 객체의 SOPInstanceUID"

      - name: modality
        type: text
        comment: "SR 또는 RDSR"

      - name: study_date
        type: date
        comment: "검사 날짜"

      - name: patient_id
        type: text
        comment: "환자 ID"

      - name: patient_sex
        type: text
        comment: "환자 성별"

      - name: patient_birth_date
        type: date
        comment: "환자 생년월일"

      - name: patient_age
        type: text
        comment: "환자 나이 (DICOM 형식)"

      - name: body_part_examined
        type: text
        comment: "검사 부위"

      - name: manufacturer
        type: text
        comment: "장비 제조사"

      - name: model_name
        type: text
        comment: "장비 모델명"

      - name: dose_data
        type: jsonb
        comment: "DLP, CTDIvol, Acquisition Parameters 등 선량 세부 정보 (JSON 형식)"

      - name: extracted_by
        type: text
        comment: "데이터 추출에 사용된 코드 버전 또는 도구 이름"

      - name: extracted_at
        type: timestamp
        default: now()
        comment: "데이터가 추출되어 저장된 시간"
