# batch_retrieving: daily_retrieving.start_date 이전까지 수행되는 과거의 검사들에 대한 야간 일괄 추출 작업
batch_retrieving:
  start_date: "20240101"         # batch 작업을 적용하는 기점일
  start_time: "02:00"            # 야간 배치 시작 시간
  end_time: "06:00"              # 야간 배치 종료 시간
  batch_days: 365                  # 한 번에 처리할 날짜수
# daily_retrieving: 날마다 추가되는 신규검사들을 주간에 추출하는 작업
daily_retrieving:
  start_date: "20250508"         # 일상적인 자동 수집 시작일
  start_time: "08:00"            # 주간 수집 시작 시간
  end_time: "18:00"              # 주간 수집 종료 시간
  time_interval: 60              # 주간 수집 간격 (분 단위)

# end_time 이후부터 익일 start_time까지의 검사가 있다면 익일 start_time 한시간 전에 retrieving 되도록 내부적으로 구현됨
